name: Setup Tools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Run commands over SSH
      run: |
        ssh -i /ruta/a/tu/llave.pem ubuntu@172.31.25.156 '
          chmod +x /00_ec2/ec2_user_data.sh &&
          /00_ec2/ec2_user_data.sh
        '
